'use client'
import {useEffect,useRef,useState} from 'react'
import {request} from '@/lib/client/request.mjs'
import {todayInZone} from '@/lib/domain/handover.mjs'
export default function SitePackage({site,actor}){
 const [start,setStart]=useState(''),[end,setEnd]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState(false),lock=useRef(false)
 useEffect(()=>{queueMicrotask(()=>{setStart(todayInZone());setEnd(todayInZone())})},[])
 async function download(e){e.preventDefault();if(lock.current)return;lock.current=true;setBusy(true);setError('');setSaved(false);try{
 const blob=await request('/api/sites/'+site.id+'/package?'+new URLSearchParams({start,end}),{method:'POST',headers:{'x-expected-actor':actor},timeoutMs:120000},'blob'),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='site-evidence-'+start+'-'+end+'.zip';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setSaved(true)
 }catch(e){setError(e.message)}finally{lock.current=false;setBusy(false)}}
 return <section aria-labelledby="site-package"><h2 id="site-package" tabIndex={-1}>Evidence package</h2><p>Download permitted site records and retained evidence for a date range. Original reports, separate amendments and follow-up history remain distinct.</p><details><summary>What is included and package limits</summary><p>Dates use America/Toronto. Briefing versions use recorded time; concerns use submission time; reports/amendments use finalization time; action history uses event time. Current follow-up is labelled as of generation, not historical status. Parents outside the range are referenced. Retained PDFs are copied unchanged; open a finalized report to generate its PDF first if needed.</p><p>Maximum 31 days, 200 activity records, 100 files, 64 MiB total and 16 MiB per file. All attachments must pass integrity checks. A change during generation requires a retry. No partial package is reported as complete. Downloads stay private; no public link is created. This is not certification or an atomic database-and-storage snapshot.</p></details><form onSubmit={download} className="handover-filters"><div><label htmlFor="package-from">Package from</label><input id="package-from" type="date" required value={start} disabled={busy} onChange={e=>{setStart(e.target.value);setSaved(false)}}/></div><div><label htmlFor="package-through">Package through</label><input id="package-through" type="date" required value={end} disabled={busy} onChange={e=>{setEnd(e.target.value);setSaved(false)}}/></div><button disabled={busy}>{busy?'Preparing evidence package…':error?'Retry evidence package':'Download evidence package'}</button></form>{busy&&<p role="status">Preparing and checking every included file. Keep this page open.</p>}{error&&<p role="alert">{error}</p>}{saved&&<p role="status">Complete package received; download requested. Open index.html inside the ZIP. If the download is interrupted or unavailable, retry here.</p>}</section>
}
