'use client'
import {useEffect,useRef,useState} from 'react'
import {request} from '@/lib/client/request.mjs'
import {HANDOVER_ZONES,validHandoverDate,todayInZone,handoverTime,handoverState,actionLink,originalLink} from '@/lib/domain/handover.mjs'
export default function SiteHandover({site,actor,date,timezone}){
 const [day,setDay]=useState(date||''),[zone,setZone]=useState(timezone||'America/Toronto'),[data,setData]=useState(null),[busy,setBusy]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),lock=useRef(false),sequence=useRef(0),root=useRef(null)
 const key='tradesafe:handover-navigation:'+actor+':'+site.id
 const endpoint=(d,z)=>'/api/sites/'+site.id+'/handover?'+new URLSearchParams({date:d,timezone:z})
 function remember(d,z){const url=new URL(window.location.href);url.searchParams.set('date',d);url.searchParams.set('timezone',z);window.history.replaceState(null,'',url);try{sessionStorage.setItem(key,JSON.stringify({date:d,timezone:z}))}catch{}}
 async function load(d,z,rememberChoice=true){if(lock.current)return;lock.current=true;setBusy(true);setError('');setNotice('');setData(null);if(rememberChoice)remember(d,z);const seq=++sequence.current;try{const next=await request(endpoint(d,z),{headers:{'x-expected-actor':actor}});if(seq===sequence.current)setData(next)}catch(e){if(seq===sequence.current)setError(e.message)}finally{if(seq===sequence.current){lock.current=false;setBusy(false)}}}
 useEffect(()=>{
  let stored;try{stored=JSON.parse(sessionStorage.getItem(key)||'null')}catch{}
  const z=HANDOVER_ZONES.includes(timezone)?timezone:HANDOVER_ZONES.includes(stored?.timezone)?stored.timezone:'America/Toronto',d=validHandoverDate(date)?date:validHandoverDate(stored?.date)?stored.date:todayInZone(z)
  queueMicrotask(()=>{setDay(d);setZone(z);void load(d,z,false)})
  // Site/actor changes remount this component. Only navigation preferences are stored.
  // eslint-disable-next-line react-hooks/exhaustive-deps
 },[])
 async function download(){if(lock.current)return;lock.current=true;setBusy(true);setError('');setNotice('');try{const blob=await request(endpoint(data.date,data.timezone)+'&download=1',{headers:{'x-expected-actor':actor}},'blob'),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='site-handover-'+site.id+'-'+data.date+'.html';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice('Handover downloaded from a fresh authorized snapshot. Its generation time is recorded in the file.')}catch(e){setError(e.message)}finally{lock.current=false;setBusy(false)}}
 useEffect(()=>{if(!data)return;let saved;try{saved=JSON.parse(sessionStorage.getItem(key)||'null')}catch{};if(saved?.returning&&saved.date===data.date&&saved.timezone===data.timezone){const details=[...root.current.querySelectorAll('details')];for(const [i,d] of details.entries())d.open=!!saved.open?.includes(i);requestAnimationFrame(()=>requestAnimationFrame(()=>window.scrollTo(0,Math.max(0,Number(saved.scroll)||0))));try{sessionStorage.setItem(key,JSON.stringify({...saved,returning:false}))}catch{}}},[data,key])
 function leave(e){if(!data||!e.target.closest('a[href]'))return;try{sessionStorage.setItem(key,JSON.stringify({date:data.date,timezone:data.timezone,returning:true,scroll:window.scrollY,open:[...root.current.querySelectorAll('details')].flatMap((d,i)=>d.open?[i]:[])}))}catch{}}
 const time=value=>handoverTime(value,data.timezone)
 return <section ref={root} onClickCapture={leave} className="site-handover" aria-labelledby="handover-title"><h2 id="handover-title">Daily handover</h2><p>Selected-day activity and current outstanding work, limited to records your account can access.</p>
 <form onSubmit={e=>{e.preventDefault();void load(day,zone)}} className="handover-filters"><div><label htmlFor="handover-date">Handover date</label><input id="handover-date" type="date" required min="2000-01-01" max="2100-12-31" value={day} disabled={busy} onChange={e=>setDay(e.target.value)}/></div><div><label htmlFor="handover-zone">Day timezone</label><select id="handover-zone" value={zone} disabled={busy} onChange={e=>setZone(e.target.value)}>{HANDOVER_ZONES.map(z=><option key={z}>{z}</option>)}</select></div><button disabled={busy}>Show day</button></form>
 {busy&&<p role="status">Loading complete handover…</p>}{error&&<div role="alert"><p>{error}</p><button disabled={busy} onClick={()=>load(day,zone)}>Retry handover</button></div>}{notice&&<p role="status">{notice}</p>}
 {data&&<><p role="status">Refreshed {time(data.generatedAt)}. Selected day: {data.date} ({data.timezone}).</p><div className="work-buttons"><button className="primary" disabled={busy||day!==data.date||zone!==data.timezone} onClick={download}>Download handover</button><button disabled={busy} onClick={()=>load(data.date,data.timezone)}>Refresh summary</button></div><p>{day!==data.date||zone!==data.timezone?'Select Show day to load your changed date or timezone before downloading. ':''}Download creates a fresh snapshot. Activity dates use server-recorded times, not entered work/observation dates. Current status does not reconstruct a past day.</p>
 <h3>Outstanding now ({data.outstanding.length})</h3><p>{data.outstanding.filter(a=>a.state==='awaiting_verification').length} awaiting verification · {data.outstanding.filter(a=>a.needs_reassignment).length} need assignment or reassignment. Includes earlier unresolved work.</p>{data.outstanding.length?<ul className="handover-list">{data.outstanding.map(a=><li key={a.id}><a href={actionLink(a,data.site)}>{a.observation}</a><p>{handoverState[a.state]} · {a.responsible}{a.needs_reassignment?' — needs assignment/reassignment':''}</p><details><summary>Progress and original record</summary><p>{a.resolution||'No progress recorded.'}</p><p>Due: {a.target_date||'Not recorded'}</p><a href={originalLink(a)}>Open original record</a></details></li>)}</ul>:<p>No outstanding actions available to your account at this site.</p>}
 <details><summary>Briefing versions recorded that day ({data.briefs.length})</summary>{data.briefs.length?data.briefs.map(b=><article key={b.id+':'+b.version}><a href={'/briefs/'+b.id+'?version='+b.version}>Brief version {b.version}: {b.task}</a><p>{b.acknowledgements.length} of {b.participants.length} acknowledged this exact version, as of refresh.</p><details><summary>Participants and recording details</summary><p>Recorded by {b.recordedBy} at {time(b.recordedAt)}. Entered work date: {b.workDate}.</p><ul>{b.participants.map(id=>{const a=b.acknowledgements.find(a=>a.userId===id);return <li key={id}>{b.people?.find(p=>p.id===id)?.name||a?.name||'Former member'}: {a?'Acknowledged at '+time(a.at):'No acknowledgement recorded'}</li>})}</ul><p>Attendance entered by recorder: {b.attendance.map(id=>b.people?.find(p=>p.id===id)?.name||'Former member').join(', ')||'None recorded'}.</p></details></article>):<p>No briefing versions recorded that day are available to your account.</p>}<p>Missing acknowledgement does not establish absence. Attendance is separate from authenticated acknowledgement; neither proves understanding or qualification. Revised versions need their own acknowledgement.</p></details>
 <details><summary>Concerns submitted that day ({data.concerns.length})</summary>{data.concerns.length?data.concerns.map(c=><article key={c.id}><a href={'/concerns/'+c.id}>{c.document.observation}</a><p>{c.document.location}</p><p>{c.reporter} · Submitted {time(c.submitted_at)}</p></article>):<p>No submitted concerns for that day are available to your account.</p>}</details>
 <details><summary>Verified closed that day ({data.closures.length} events)</summary>{data.closures.length?data.closures.map(a=><article key={a.eventId}><a href={actionLink(a,data.site)}>{a.observation}</a><p>Verified by {a.verifiedBy} at {time(a.at)}. Responsible at verification: {a.responsible}.</p><p>Current status: {handoverState[a.currentState]}</p><details><summary>Resolution at verification</summary><p>{a.resolution}</p><a href={originalLink(a)}>Open original record</a></details></article>):<p>No verification events for that day are available to your account.</p>}<p>Verification events remain visible if an action is later reopened. A closed action does not certify the site safe.</p></details></>}
 </section>
}
