'use client'
import {useEffect,useRef,useState} from 'react'
import {request} from '@/lib/client/request.mjs'
import {useClientReady} from '@/lib/client/useClientReady'
import {todayInZone,handoverTime} from '@/lib/domain/handover.mjs'
const types={all:'All records',brief:'Briefing versions',concern:'Submitted concerns',report:'Finalized reports',amendment:'Amendments',action:'Action events'}
export default function SiteHistory({site,actor}){
 const [filters,setFilters]=useState({start:'',end:'',kind:'all',q:''}),[data,setData]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),pending=useRef(null),lock=useRef(false),restore=useRef(null)
 const key='tradesafe:site-history:'+actor+':'+site.id
 const ready=useClientReady(),disabled=!ready||!filters.start||busy
 async function load(f){if(lock.current)return;lock.current=true;pending.current=f;setBusy(true);setError('');setData(null);try{const d=await request('/api/sites/'+site.id+'/history?'+new URLSearchParams(f),{headers:{'x-expected-actor':actor}});setData(d);setFilters(f);try{sessionStorage.setItem(key,JSON.stringify({filters:{...f,cutoff:d.cutoff}}))}catch{};if(restore.current!=null){const y=restore.current;restore.current=null;requestAnimationFrame(()=>requestAnimationFrame(()=>window.scrollTo(0,y)))}}catch(e){setError(e.message)}finally{lock.current=false;setBusy(false)}}
 useEffect(()=>{let stored;try{stored=JSON.parse(sessionStorage.getItem(key)||'null')}catch{};const day=todayInZone();queueMicrotask(()=>{const f=stored?.filters||{start:day,end:day,kind:'all',q:''};setFilters(f);if(stored?.returning){restore.current=stored.scroll;void load(f)}})
 // Only navigation preferences, never record content, are stored.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 },[])
 function leave(){try{sessionStorage.setItem(key,JSON.stringify({filters:{...filters,cutoff:data.cutoff},returning:true,scroll:scrollY}))}catch{}}
 const link=r=>r.kind==='brief'?'/briefs/'+r.record_id+'?version='+r.revision:r.kind==='concern'?'/concerns/'+r.record_id:r.kind==='action'?'/actions?'+new URLSearchParams({company:site.company_id,site:site.id,mine:'0',status:'all',focus:r.record_id}):'/report/'+r.record_id+'?'+new URLSearchParams({from:'/sites/'+site.id})
 return <section aria-labelledby="site-history"><h2 id="site-history" tabIndex={-1}>Site history</h2><p>Recorded activity in America/Toronto. Search text you are permitted to read; current action status is separate from the historical event. Up to 366 days per search.</p><form className="handover-filters" onSubmit={e=>{e.preventDefault();void load({start:filters.start,end:filters.end,kind:filters.kind,q:filters.q})}}><label>History from<input disabled={disabled} type="date" required value={filters.start} onChange={e=>setFilters({...filters,start:e.target.value})}/></label><label>History through<input disabled={disabled} type="date" required value={filters.end} onChange={e=>setFilters({...filters,end:e.target.value})}/></label><label>Record type<select disabled={disabled} value={filters.kind} onChange={e=>setFilters({...filters,kind:e.target.value})}>{Object.entries(types).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Search site history<input disabled={disabled} type="search" maxLength={120} value={filters.q} onChange={e=>setFilters({...filters,q:e.target.value})}/></label><button disabled={disabled}>Search history</button></form>
 {busy&&<p role="status">Loading history…</p>}{error&&<div role="alert"><p>{error}</p><button disabled={busy} onClick={()=>load(pending.current)}>Retry history</button></div>}{data&&<><p role="status">{data.rows.length} records on this page. Activity cutoff: {handoverTime(data.cutoff,data.timezone)}.</p>{data.rows.length?<ul className="work-list">{data.rows.map(r=><li key={r.event_key}><a href={link(r)} onClick={leave}><strong>{r.title||types[r.kind]}</strong><span>{types[r.kind]} · {site.document.name}</span><span>{handoverTime(r.occurred_at,data.timezone)} · {r.event_status}{r.kind==='brief'?' · Version '+r.revision:''}</span></a>{r.current_status&&<p>Current action status at search: {r.current_status.replaceAll('_',' ')}</p>}</li>)}</ul>:<p>No permitted records match these dates and filters.</p>}{data.more&&<button disabled={busy} onClick={()=>{const last=data.rows.at(-1);void load({...filters,cutoff:data.cutoff,before:last.occurred_at,key:last.event_key})}}>Next history page</button>}{filters.before&&<button disabled={busy} onClick={()=>load({start:filters.start,end:filters.end,kind:filters.kind,q:filters.q,cutoff:data.cutoff})}>First history page</button>}</>}
 </section>
}
