'use client'
import {useEffect,useRef,useState} from 'react'
import {ACTION_VIEWS,actionListUrl,matchesAction} from '@/lib/domain/action-list'
import {useClientReady} from '@/lib/client/useClientReady'
import {useUnsavedWarning} from '@/lib/client/useUnsavedWarning'
import {command} from '@/lib/client/commands'
import {canVerify,canEditReport,ACTION_STATES} from '@/lib/domain/inspection'
import {canUpdateAction,needsResolution,definitiveActionFailure,ACTION_LABELS} from '@/lib/domain/action-edit'
function Action({initial,amendments,members,events,role,actor,companyId,onSaved,onSaving,hidden,returnTo,selected,onSelect,outside}){
 const [action,setAction]=useState(initial),[edit,setEdit]=useState(initial),[error,setError]=useState(''),[errorCode,setErrorCode]=useState(''),[busy,setBusy]=useState(false),[history,setHistory]=useState(events),[updated,setUpdated]=useState(false),[uncertain,setUncertain]=useState(false)
 const ready=useClientReady(),pending=useRef(null),lock=useRef(false),editable=canUpdateAction(role,actor,action)
 const dirty=['controls','resolution','state','responsible_id','target_date'].some(k=>edit[k]!==action[k])
 useUnsavedWarning(dirty||uncertain)
 function change(key,value){setEdit(e=>({...e,[key]:value}));setUpdated(false)}
 async function save(e){e.preventDefault();if(lock.current||!ready||!editable)return;lock.current=true;setBusy(true);setError('');setErrorCode('');setUpdated(false);onSaving();try{
  pending.current||={companyId,id:action.id,revision:action.revision,requestId:crypto.randomUUID(),state:edit.state,controls:edit.controls,responsibleId:edit.responsible_id,targetDate:edit.target_date||'',resolution:edit.resolution}
  const value={...await command('update_action',pending.current,actor),report:action.report,brief:action.brief};pending.current=null;setUncertain(false);setAction(value);setEdit(value);setHistory([]);setUpdated(true);onSaved(value)
 }catch(e){setError(e.code==='incomplete'?'Add resolution notes before requesting verification or closing this action. Your entries are still here.':e.code==='invalid_request'?'Check the assignee, due date and update fields, then save again. Your entries are still here.':e.message);setErrorCode(e.code);if(definitiveActionFailure(e.code)){pending.current=null;setUncertain(false)}else setUncertain(true)}finally{lock.current=false;setBusy(false)}}
 const origin=action.brief_id?'/briefs/'+action.brief_id+'?'+new URLSearchParams({version:String(action.brief_version),from:returnTo}):'/report/'+action.report_id+'?'+new URLSearchParams({from:returnTo})
 const name=id=>members.find(m=>m.user_id===id)?.display_name||'Former or unavailable member',blocked=['conflict','denied','immutable','not_found'].includes(errorCode)
 return <article hidden={hidden} tabIndex={-1} className="work-panel action-card" id={'action-'+action.id}>
 {outside&&<p className="work-notice">Selected action is outside the current filter. Your list filters are preserved.</p>}
 <h2><a href={origin}>{action.brief?.document?.site||action.report?.document?.job?.address||'Original record'}{action.report?.amendment_of?' (amendment)':''}</a></h2>
 <h3>Original finding</h3><p className="action-observation">{action.observation}</p><div className="action-summary"><p><strong>{ACTION_LABELS[action.state]}</strong></p><p>Assigned to: {name(action.responsible_id)}{action.responsible_id===actor?' (you)':''}</p><p>Due: {action.target_date||'No due date'}</p></div>
 <div className="action-progress"><h3>Latest saved progress</h3><p>{action.resolution||'No progress notes recorded yet.'}</p>{action.controls&&<p>Immediate controls: {action.controls}</p>}</div>
 {(!editable||['closed','awaiting_verification'].includes(action.state))&&<p className="action-next">{!editable?(action.state==='closed'?'Verified and completed. Only a supervisor or owner can reopen it.':'The assigned worker, a supervisor or an owner can update this action.'):action.state==='closed'?'Reopen this action if more work is needed. Previous verification stays in history.':action.state==='awaiting_verification'?(canVerify(role)?'Review the resolution and evidence, then verify and close if appropriate.':'Awaiting a supervisor or owner. You can still record further progress.'):'Record progress, then request verification when ready.'}</p>}
 {dirty&&<p role="status">Unsaved changes — save below before leaving.</p>}
 <details className="action-editor" open={selected||undefined} onToggle={e=>{if(e.target===e.currentTarget&&e.currentTarget.open)onSelect(action.id)}}><summary>{editable?(action.state==='closed'?'Reopen action':action.state==='awaiting_verification'&&canVerify(role)?'Review and verify':'Update progress'):'View action details'}</summary>
 {action.verified_at&&<p>Verified by {name(action.verified_by)} on {new Date(action.verified_at).toLocaleString('en-CA')}</p>}
 {editable?<form onSubmit={save}><fieldset disabled={!ready||busy||uncertain||blocked} className="work-fieldset">
 <label htmlFor={'state-'+action.id}>Status after saving</label><select id={'state-'+action.id} value={edit.state} onChange={e=>change('state',e.target.value)}>{ACTION_STATES.filter(s=>(canVerify(role)||s!=='closed')&&(action.state!=='closed'||['closed','open'].includes(s))).map(s=><option key={s} value={s}>{ACTION_LABELS[s]}</option>)}</select>
 <label htmlFor={'resolution-'+action.id}>Progress or resolution notes</label><textarea id={'resolution-'+action.id} maxLength={4000} required={needsResolution(edit.state)} value={edit.resolution} onChange={e=>change('resolution',e.target.value)} aria-describedby={needsResolution(edit.state)?'resolution-help-'+action.id:undefined}/>
 {needsResolution(edit.state)&&<p id={'resolution-help-'+action.id}>Describe the resolution before requesting verification or closing the action.</p>}
 <details><summary>Assignment, due date and immediate controls</summary> <label htmlFor={'controls-'+action.id}>Immediate controls or action taken</label><textarea id={'controls-'+action.id} value={edit.controls} maxLength={4000} onChange={e=>change('controls',e.target.value)}/>
 {canVerify(role)&&<><label htmlFor={'responsible-'+action.id}>Responsible member</label><select id={'responsible-'+action.id} value={edit.responsible_id} onChange={e=>change('responsible_id',e.target.value)}>{members.filter(m=>m.active||m.user_id===edit.responsible_id).map(m=><option key={m.user_id} value={m.user_id} disabled={!m.active}>{m.display_name}{m.active?'':' (removed — reassign)'}</option>)}</select></>}
 <label htmlFor={'target-'+action.id}>Due date (optional)</label><input id={'target-'+action.id} type="date" value={edit.target_date||''} onChange={e=>change('target_date',e.target.value)}/>
</details>
 {!canVerify(role)&&<p>You can update your assigned action and request verification. A supervisor or owner assigns members and verifies closure.</p>}
 {edit.state==='closed'&&action.state!=='closed'&&<p>Saving records you as the verification actor. Your app role does not establish statutory competence.</p>}
 {action.state==='closed'&&<p>Select Open to reopen. Previous resolution and verification remain in the history.</p>}
 </fieldset>{uncertain&&<p>Keep this page open and retry the same update. Your entries are retained; its result has not been confirmed.</p>}<button className="primary" disabled={!ready||busy||blocked||(action.state==='closed'&&edit.state!=='open')}>{busy?'Saving…':uncertain?'Retry action update':action.state==='closed'?'Reopen action':edit.state==='closed'?'Verify and close':edit.state==='awaiting_verification'&&action.state!=='awaiting_verification'?'Request verification':'Save progress'}</button>
 {busy&&<p role="status">Saving action update. Keep this page open.</p>}{updated&&<p role="status">Action update saved.</p>}{error&&<div role="alert"><p>{error}</p>{blocked?<><p>Your entries are still here. Compare the latest saved action in another tab before discarding them. Do not keep retrying an outdated or unauthorized update.</p><a href={actionListUrl(companyId,{mine:false,status:'all',page:0,focus:action.id})} target="_blank" rel="noopener noreferrer">Open latest saved action</a></>:(!definitiveActionFailure(errorCode)||errorCode==='account_changed')&&<a href={'/auth/login?'+new URLSearchParams({redirect:returnTo})} target="_blank" rel="noopener noreferrer">Sign in in another tab, then retry here</a>}</div>}</form>:<><p>{action.controls||'No immediate controls recorded.'}</p><p>{action.resolution||'No resolution recorded.'}</p><p>{action.state==='closed'?'This action is verified and closed. A supervisor or owner can reopen it.':'Only the assigned worker, a supervisor or an owner can update this action.'}</p></>}
 <div className="action-evidence">{action.brief_id?<><h3>Original daily brief</h3><a href={origin+'#hazard-'+action.item_id}>Open original hazard and control</a><p>This action preserves the finding from brief version {action.brief_version}. Progress here does not change that version. Review the current brief and record an explicit revision if the assessment changes.</p><a href={'/briefs/'+action.brief_id+'?'+new URLSearchParams({from:returnTo})}>Open current daily brief</a></>:<><h3>Finding and correction evidence</h3><a href={'/report/'+action.report_id+'?'+new URLSearchParams({from:returnTo})+'#observation-'+action.item_id}>Open original observation</a><p>Original photos stay locked. Add correction photos in a separate amendment, then return here to record the resolution. An amendment does not close this action.</p>{canEditReport(role,actor,action.report?.author_id)?<a className="button" href={'/report/'+action.report_id+'?'+new URLSearchParams({from:returnTo,action:action.id})+'#amend-report'}>Add correction evidence</a>:<p>Ask the original author, a supervisor or an owner to add an amendment with correction photos.</p>}<details><summary>Amendments to this report ({amendments.length})</summary><p>These amendments belong to the report; they are not automatically a resolution of this action.</p>{amendments.length?<ul>{amendments.map(r=><li key={r.id}><a href={'/report/'+r.id+'?'+new URLSearchParams({from:returnTo})}>{r.amendment_reason} ({r.lifecycle})</a><ul>{r.photos.filter(p=>p.state==='ready').map(p=><li key={p.id}><a href={'/api/reports/'+r.id+'/evidence/'+p.id} target="_blank" rel="noopener noreferrer">Photo: {p.caption}</a></li>)}</ul></li>)}</ul>:<p>No amendment evidence recorded yet.</p>}</details></>}</div>
 <details><summary>Action history</summary>{history.length?<ol>{[...history].reverse().map(e=><li key={e.id}><strong>{e.kind.replaceAll('_',' ')}</strong> · {name(e.actor_id)} · {new Date(e.occurred_at).toLocaleString('en-CA')}<p>{e.before_value?.state?ACTION_LABELS[e.before_value.state]+' → ':''}{ACTION_LABELS[e.after_value?.state]}</p>{e.after_value?.resolution&&<p>Resolution: {e.after_value.resolution}</p>}{e.after_value?.controls&&<p>Controls: {e.after_value.controls}</p>}</li>)}</ol>:<p>{updated?'Update saved. ':''}<a href={actionListUrl(companyId,{mine:false,status:'all',page:0,focus:action.id})} target="_blank" rel="noopener noreferrer">Open recorded history in another tab</a></p>}<p className="work-footnote">History includes up to 500 recent events for actions on this page.</p></details></details></article>
}
export default function ActionList({initial,amendments=[],members,events,actor,role,companyId,filters,initialCounts}){
 const [actions,setActions]=useState(initial),[counts,setCounts]=useState(initialCounts),[selected,setSelected]=useState(filters.focus),[message,setMessage]=useState('')
 const visible=a=>matchesAction(a,filters,actor),filtered=actions.filter(visible),total=counts[filters.status]
 useEffect(()=>{if(filters.focus){const card=document.getElementById('action-'+filters.focus);card?.focus({preventScroll:true});card?.scrollIntoView({block:'start'})}},[filters.focus])
 function select(id){setSelected(id);window.history.replaceState(null,'',actionListUrl(companyId,{...filters,focus:id}))}
 const saved=value=>{const previous=actions.find(a=>a.id===value.id);setCounts(current=>Object.fromEntries(Object.entries(current).map(([status,count])=>[status,count-Number(matchesAction(previous,{...filters,status},actor))+Number(matchesAction(value,{...filters,status},actor))])));setActions(rows=>rows.map(a=>a.id===value.id?value:a));setMessage('Action update saved. Counts now reflect this update.')}
 return <><form action="/actions" className="action-filters">{filters.site&&<input type="hidden" name="site" value={filters.site}/>}<input type="hidden" name="company" value={companyId}/><label htmlFor="action-scope">Whose actions?</label><select id="action-scope" name="mine" defaultValue={filters.mine?'1':'0'}><option value="1">Assigned to me</option><option value="0">Company actions</option></select><label htmlFor="action-view">Work status</label><select id="action-view" name="status" defaultValue={filters.status}>{Object.entries(ACTION_VIEWS).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><button type="submit">Show actions</button></form>
 <nav className="action-overview" aria-label="Follow-up status">{['attention','awaiting_verification','closed'].map(status=><a key={status} aria-current={filters.status===status?'page':undefined} href={actionListUrl(companyId,{...filters,status,page:0,focus:''})}>{counts[status]} {ACTION_VIEWS[status]}</a>)}</nav>
 <p role="status">{total} matching {total===1?'action':'actions'}{total>25?' · 25 per page':''}. Sorted by due date.</p>
 {message&&<p role="status">{message}</p>}{!filtered.length&&<section className="work-panel"><h2>{total?'No actions on this page':filters.status==='awaiting_verification'?'Nothing awaiting verification':filters.status==='closed'?'No completed actions':filters.mine?'No matching actions assigned to you':'No matching company actions'}</h2><p>{filters.status==='closed'?'Verified actions appear here after a supervisor or owner closes them.':'Actions come from finalized report findings or recorded daily briefs needing follow-up. Try another status or the company list.'}</p><a href={actionListUrl(companyId,{...filters,mine:false,status:'outstanding',page:0,focus:''})}>View company outstanding actions</a></section>}
 {actions.map(a=><Action key={a.id} initial={a} amendments={amendments.filter(r=>r.amendment_of===a.report_id)} hidden={!visible(a)&&a.id!==selected} outside={!visible(a)} selected={a.id===selected} onSelect={select} members={members} events={events.filter(e=>e.entity_id===a.id)} actor={actor} role={role} companyId={companyId} returnTo={actionListUrl(companyId,{...filters,focus:a.id})} onSaved={saved} onSaving={()=>{select(a.id);setMessage('')}}/>)}
 <nav className="work-buttons" aria-label="Action pages">{filters.page>0&&<a href={actionListUrl(companyId,{...filters,page:filters.page-1,focus:''})}>Previous actions</a>}{(filters.page+1)*25<total&&<a href={actionListUrl(companyId,{...filters,page:filters.page+1,focus:''})}>Next actions</a>}</nav></>
}
