'use client'
import {textOnly} from '@/lib/client/device-store.mjs'
export function TextFields({kind,value}){const t=textOnly(kind,value);return kind==='concern'?<dl><dt>Observation</dt><dd className="preserve-lines">{t.observation||'Not entered'}</dd><dt>Location</dt><dd>{t.location||'Not entered'}</dd><dt>Immediate steps</dt><dd className="preserve-lines">{t.immediate||'Not entered'}</dd></dl>:<><p className="preserve-lines"><strong>Today’s work:</strong> {t.task||'Not entered'}</p>{t.steps.map((s,i)=><div key={s.id}><h4>Task step {i+1}</h4><dl><dt>Task</dt><dd className="preserve-lines">{s.task||'Not entered'}</dd><dt>Hazard</dt><dd className="preserve-lines">{s.hazard||'Not entered'}</dd><dt>Control</dt><dd className="preserve-lines">{s.control||'Not entered'}</dd></dl></div>)}</>}
export default function DeviceText({device,kind,company}){const r=device.recovery;return <section className="work-panel" aria-label="Device text recovery">
 <label className="work-check"><input type="checkbox" checked={device.enabled} disabled={!device.ready||device.checking} onChange={e=>device.toggle(e.target.checked)}/>Keep unfinished text on this device</label>
 <details><summary>Device storage and privacy</summary><p>Only concern text/location and daily-brief work/hazard/control text. No photos, passwords, acknowledgements or submission commands. This browser may be shared. Text is not encrypted by this feature and is not a backup. Browser data may be cleared.</p><p>Expires 7 days after the last local edit; up to 10 drafts, 1 MiB total and 128 KiB per draft. Expired or unreadable copies are removed when TradeSafe next checks storage. Sign out, switching accounts or opting out removes device copies. Recovery requires online sign-in and an access check; offline launching is not supported.</p></details>
 <a href={'/device-drafts?company='+company}>Device drafts</a>
 {device.error&&<p role="alert">{device.error}</p>}
 {device.savedAt&&!device.error&&<p role="status">Saved on this device; upload pending. Last local save: {new Date(device.savedAt).toLocaleString()}.</p>}
 {r&&<><h2>{r.local.revision===(r.server?.revision||0)?'Recover unfinished text':'Server changes require review'}</h2><p>No recovered text has been uploaded by this page. Compare these fields; choosing device text explicitly replaces them on the current draft. Changed controls return to Proposed. Other server fields remain unchanged.</p><details open><summary>Compare device and server text</summary><h3>On this device</h3><TextFields kind={kind} value={r.local.text}/><h3>Current server text</h3><TextFields kind={kind} value={r.server?.document}/></details>{r.editable?<div className="work-buttons"><button type="button" disabled={device.checking} onClick={()=>device.resolve(true)}>Use device text in current draft</button><button type="button" disabled={device.checking} onClick={()=>device.resolve(false)}>Keep server text</button></div>:<p>This record is no longer editable. No submission, acknowledgement or revision will be replayed. Remove the copy in Device drafts when no longer needed.</p>}</>}
 {!r&&device.error&&<button type="button" disabled={device.checking} onClick={device.inspect}>Check access and device draft again</button>}
 </section>}
