'use client'
import {useTransition,useSyncExternalStore} from 'react'
import {useRouter} from 'next/navigation'
import {reportFilters,reportListUrl} from '@/lib/domain/report-list'
const subscribe=()=>()=>{},clientReady=()=>true,serverReady=()=>false
export default function ListSearch({company,q,status,trade,sort,site}){
 const ready=useSyncExternalStore(subscribe,clientReady,serverReady)
 const router=useRouter(),[pending,start]=useTransition()
 function submit(e){e.preventDefault();const data=new FormData(e.currentTarget);start(()=>router.push(reportListUrl(company,reportFilters(Object.fromEntries(data)))))}
 return <form action="/reports" className="library-search" onSubmit={submit} aria-busy={pending}><fieldset className="work-fieldset" disabled={pending||!ready}>{site&&<input type="hidden" name="site" value={site}/>}<input type="hidden" name="company" value={company}/><label htmlFor="report-search">Customer, job or site</label><input id="report-search" name="q" type="search" maxLength={120} defaultValue={q} placeholder="Search an address or customer"/><div className="library-filters"><div><label htmlFor="status">Report status</label><select name="status" id="status" defaultValue={status}><option value="">All reports</option><option value="draft">Drafts to resume</option><option value="finalized">Finalized reports</option><option value="amended">Amendments (draft and finalized)</option></select></div><div><label htmlFor="trade">Trade</label><select id="trade" name="trade" defaultValue={trade}><option value="">All trades</option><option value="electrical">Electrical</option><option value="plumbing">Plumbing</option><option value="roofing">Roofing</option></select></div><div><label htmlFor="sort">Sort by</label><select id="sort" name="sort" defaultValue={sort}><option value="recent">Recently updated</option><option value="oldest">Oldest update first</option><option value="work_date">Newest work date</option></select></div></div><div className="work-buttons"><button className="primary" disabled={pending}>{pending?'Finding reports...':'Find reports'}</button><a href={'/reports?company='+company+(site?'&site='+site:'')}>Clear filters</a></div></fieldset>{pending&&<p role="status">Loading matching reports. Your filters stay in the address bar.</p>}</form>
}
