import {test} from 'node:test'
import assert from 'node:assert/strict'
import {randomUUID} from 'node:crypto'
import {PREFIX,TTL,entries,writeDraft,readDraft,textOnly,applyText,removeAll} from '../lib/client/device-store.mjs'
import {safeRedirect} from '../lib/domain/validation.ts'
const storage=()=>{const s={};Object.defineProperties(s,{getItem:{value:k=>s[k]??null},setItem:{value:(k,v)=>s[k]=v},removeItem:{value:k=>delete s[k]}});return s}
const scope=()=>({actor:randomUUID(),company:randomUUID(),kind:'concern',id:randomUUID(),siteId:randomUUID()})
test('device drafts whitelist text, bind namespace and baseline, confirm writes and reject another tab',()=>{const s=storage(),a=scope(),v=writeDraft(s,a,{revision:2,text:{observation:'Unsent',location:'Bay',password:'excluded',photo:'excluded'},baseline:{observation:'Server'}},null,100);assert.equal(readDraft(s,a,101).text.observation,'Unsent');assert.equal(v.revision,2);assert.ok(!JSON.stringify(v).includes('excluded'));assert.equal(readDraft(s,{...a,actor:randomUUID()},101),null);assert.throws(()=>writeDraft(s,a,{text:{}},null,102),/Another tab/);assert.equal(readDraft(s,a,103).text.observation,'Unsent')})
test('expiry/corruption and logout cleanup do not touch unrelated storage',()=>{const s=storage(),a=scope();writeDraft(s,a,{text:{observation:'old'}},null,100);s[PREFIX+'corrupt']='not json';s.unrelated='keep';assert.equal(entries(s,100+TTL).length,0);writeDraft(s,a,{text:{}},null,100+TTL);removeAll(s);assert.deepEqual(Object.keys(s),['unrelated'])})
test('limits and denied/full writes preserve previously confirmed drafts',()=>{const s=storage();for(let i=0;i<10;i++)writeDraft(s,scope(),{text:{observation:'retained'}});assert.throws(()=>writeDraft(s,scope(),{text:{}}),/limit/);assert.equal(entries(s).length,10);const denied=storage();Object.defineProperty(denied,'x',{value:1});assert.throws(()=>writeDraft({getItem:()=>null,setItem:()=>{throw Error('denied')},removeItem:()=>{}},scope(),{text:{}}),/denied/)})
test('brief recovery never restores acknowledgement, crew or implemented state from device text',()=>{const id=randomUUID(),server={task:'Old',crew:['server crew'],attendance:['server attendance'],steps:[{id,task:'Old',hazard:'Old',control:'Old',controlState:'reported_implemented',responsible:'server member',unresolved:true}]},local={task:'New',crew:['forged'],steps:[{id,task:'Step',hazard:'New',control:'New',controlState:'reported_implemented',responsible:'forged'}]};const p=textOnly('brief',local);assert.deepEqual(Object.keys(p),['task','steps']);const result=applyText('brief',server,p);assert.equal(result.steps[0].controlState,'proposed');assert.equal(result.steps[0].responsible,'server member');assert.deepEqual(result.crew,server.crew);assert.deepEqual(result.attendance,server.attendance)})
test('recovery destinations preserve only scoped identifiers and oversized text fails explicitly',()=>{const s=scope(),url='/concerns/new?'+new URLSearchParams({device:s.id,site:s.siteId});assert.equal(safeRedirect(url),url);assert.equal(safeRedirect('/device-drafts?company='+s.company),'/device-drafts?company='+s.company);assert.equal(safeRedirect('/concerns/new?device=invalid'),'/concerns/new');const large={task:'Large',steps:Array.from({length:20},()=>({id:randomUUID(),task:'é'.repeat(2000),hazard:'é'.repeat(2000),control:'é'.repeat(2000)}))};assert.throws(()=>writeDraft(storage(),{...s,kind:'brief'},{text:large}),/limit/)})
test('blocked reads are not treated as corrupted records and never delete retained text',()=>{let removed=false;const s={[PREFIX+'retained']:'text',getItem(){throw new DOMException('blocked','SecurityError')},removeItem(){removed=true}};assert.throws(()=>entries(s),{name:'SecurityError'});assert.equal(removed,false)})
