// Real browser/server checks. Existing synthetic account only; no account creation or email.
// Interrupted responses use route.fetch() against the real server, then abort delivery.
import {readFileSync,writeFileSync,existsSync,mkdirSync} from 'node:fs'
import {resolve} from 'node:path'
import {execFileSync} from 'node:child_process'
import {createHash,randomUUID} from 'node:crypto'
import assert from 'node:assert/strict'
import sharp from 'sharp'
import {createClient} from '@supabase/supabase-js'
import {jpegAtSize} from '../../tests/fixtures/large-photo.mjs'
import {HOSTED_ORIGIN,STAGING_PROJECT} from '../../lib/staging/hosted.mjs'
import {requireStaging} from './config.mjs'
const {env}=requireStaging(),hosted=process.argv.includes('--hosted'),label=hosted?'hosted':'local',origin=hosted?HOSTED_ORIGIN:'https://localhost:3000'
assert.equal(env.NEXT_PUBLIC_SUPABASE_URL,'https://'+STAGING_PROJECT+'.supabase.co')
const secrets=JSON.parse(readFileSync('.staging/reliability-hosted-private.json')),companyId=JSON.parse(readFileSync('.staging/reliability-hosted.json')).companyId
const filename='.staging/journey-'+label+'.json',state=existsSync(filename)?JSON.parse(readFileSync(filename)):{origin,companyId,startedAt:new Date().toISOString(),checks:[]}
assert.equal(state.origin,origin);assert.equal(state.companyId,companyId)
state.sourceCommit=execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim();state.sourceDirty=Boolean(execFileSync('git',['diff','HEAD','--name-only'],{encoding:'utf8'}).trim());state.status='RUNNING'
const save=()=>writeFileSync(filename,JSON.stringify(state,null,2)+'\n'),has=name=>state.checks.some(c=>c.name===name),pass=name=>{state.checks.push({name,at:new Date().toISOString()});save();console.log('PASS '+name)};save()
process.env.PLAYWRIGHT_BROWSERS_PATH=resolve('.staging/browsers')
const {chromium,devices,expect}=await import('@playwright/test'),gate=JSON.parse(readFileSync('.staging/hosted-access.json'))
const browser=await chromium.launch(),options={...devices['iPhone 14 Pro Max'],...(hosted?{httpCredentials:{username:gate.username,password:gate.password}}:{})},c=await browser.newContext(options)
async function login(context,account=secrets.owner){const page=await context.newPage();page.setDefaultTimeout(30000);page.setDefaultNavigationTimeout(90000);await page.goto(origin+'/auth/login',{waitUntil:'networkidle'});await page.getByLabel('Email',{exact:true}).fill(account.email);await page.getByLabel('Password',{exact:true}).fill(account.password);await page.getByRole('button',{name:'Sign In',exact:true}).click();await page.waitForURL('**/dashboard');return page}
const p=await login(c),output=resolve('test-results/journey-'+label);mkdirSync(output,{recursive:true})
const address='SYNTHETIC report journey '+label,caption='SYNTHETIC orange cone — report journey '+label,note='SYNTHETIC orange cone marks an isolated test concern.'
const ordinary=createClient(env.NEXT_PUBLIC_SUPABASE_URL,env.NEXT_PUBLIC_SUPABASE_ANON_KEY,{auth:{persistSession:false,autoRefreshToken:false}})
const saved=()=>expect(p.locator('.save-state')).toHaveText('Saved',{timeout:30000})
try{
 if(hosted){assert.match(process.env.EXPECTED_COMMIT||'',/^[a-f0-9]{40}$/);state.identity=await(await c.request.get(origin+'/api/staging/identity')).json();assert.equal(state.identity.commit,process.env.EXPECTED_COMMIT);save()}
 if(!state.reportId){
  await p.goto(origin+'/report/new?company='+companyId,{waitUntil:'networkidle'})
  // Journal the client-generated ID before sending; an uncertain response never creates another report.
  await c.route(origin+'/api/workspace',async route=>{const data=route.request().postDataJSON();if(data.command==='create_report'){state.reportId=data.payload.id;save()}await route.continue()})
  const response=p.waitForResponse(r=>r.url()===origin+'/api/workspace'&&r.request().postDataJSON()?.command==='create_report')
  await p.getByRole('button',{name:'Create saved draft',exact:true}).evaluate(b=>{b.click();b.click()});assert.equal((await response).status(),200);await p.waitForURL('**/report/'+state.reportId);await c.unroute(origin+'/api/workspace');pass('create saved synthetic report through actual UI')
 }
 const report=origin+'/report/'+state.reportId,base=report.replace('/report/','/api/reports/')+'/evidence',exports=report.replace('/report/','/api/reports/')+'/exports'
 if(!has('linked validation, draft navigation, expired session recovery and dashboard resume')){
  await p.goto(report+'?step=4',{waitUntil:'networkidle'});await p.getByRole('link',{name:'Enter the job address.',exact:true}).click();await expect(p.getByLabel('Job address',{exact:true})).toBeFocused()
  await p.getByLabel('Job address',{exact:true}).fill(address);await p.getByLabel('Work date',{exact:true}).fill('2026-09-17');await p.getByRole('button',{name:'Continue to observations',exact:true}).click();await p.getByRole('button',{name:'1. Job details',exact:true}).click();await expect(p.getByLabel('Job address',{exact:true})).toHaveValue(address);await saved()
  await c.clearCookies();await p.getByLabel('Client or job reference (optional)',{exact:true}).fill('SYNTHETIC retained after sign-in recovery');await expect(p.getByRole('alert').filter({hasText:'session has expired'})).toBeVisible({timeout:30000});await expect(p.locator('.save-state')).toHaveText('Not saved')
  const signin=await login(c);await signin.close();await p.getByRole('button',{name:'Retry saving',exact:true}).click();await saved();await p.reload({waitUntil:'networkidle'});await expect(p.getByLabel('Client or job reference (optional)',{exact:true})).toHaveValue('SYNTHETIC retained after sign-in recovery')
  await p.goto(origin+'/dashboard?company='+companyId,{waitUntil:'networkidle'});assert.equal(new URL(await p.getByRole('link',{name:'Resume latest draft',exact:true}).getAttribute('href'),origin).pathname,'/report/'+state.reportId);await p.getByRole('link',{name:'Resume latest draft',exact:true}).click();await expect(p.getByLabel('Job address',{exact:true})).toHaveValue(address)
  await p.getByRole('button',{name:'4. Review',exact:true}).click();await p.locator('.work-alert a').first().click();await expect(p.getByLabel('Observation',{exact:true}).first()).toBeFocused();await p.getByLabel('Observation',{exact:true}).first().selectOption('attention');await p.getByRole('button',{name:'4. Review',exact:true}).click();await p.getByRole('link',{name:/add an explanation/}).first().click();await expect(p.getByLabel('Explanation (required)',{exact:true})).toBeFocused();await p.getByLabel('Explanation (required)',{exact:true}).fill(note)
  const fields=p.getByLabel('Observation',{exact:true});for(let i=1;i<await fields.count();i++)await fields.nth(i).selectOption('meets');await saved();pass('linked validation, draft navigation, expired session recovery and dashboard resume')
 }
 if(!has('recognizable 3.43 MiB real upload, interruption retry, repeated taps and reload persistence')){
  await p.goto(report+'?step=5',{waitUntil:'networkidle'});await expect(p.getByText('Photo upload troubleshooting',{exact:true})).toBeVisible();assert.equal(await p.getByText('Photo upload troubleshooting',{exact:true}).evaluate(e=>e.parentElement.open),false)
  const jpeg=await sharp(Buffer.from('<svg width="1280" height="960"><rect width="1280" height="960" fill="#173e68"/><text x="80" y="110" fill="white" font-size="65">TRADESAFE SYNTHETIC TEST</text><path d="M640 240 L410 760 L870 760 Z" fill="#ff8a24"/><path d="M530 490 L750 490 L790 580 L490 580 Z" fill="white"/><rect x="370" y="760" width="540" height="60" fill="#ff8a24"/><text x="300" y="900" fill="white" font-size="48">ORANGE CONE - NO REAL JOB</text></svg>')).jpeg().toBuffer(),fixture=jpegAtSize(jpeg,3600000)
  await p.getByLabel('Photo file',{exact:true}).setInputFiles({name:'SYNTHETIC-orange-cone-3.43MiB.jpg',mimeType:'image/jpeg',buffer:fixture});await p.getByRole('button',{name:'Upload photo',exact:true}).click();await expect(p.getByRole('alert').filter({hasText:'Enter a photo caption'})).toBeVisible();await p.getByLabel('Photo caption',{exact:true}).fill(caption)
  await p.getByRole('button',{name:'Continue to review',exact:true}).click();await expect(p.getByRole('alert').filter({hasText:'has not been saved'})).toBeVisible();await p.getByRole('checkbox').check();await expect(p.getByRole('button',{name:'Finalize report',exact:true})).toBeDisabled();await p.getByRole('button',{name:'Back to photos',exact:true}).click();await expect(p.getByLabel('Photo caption',{exact:true})).toHaveValue(caption);assert.equal(await p.getByLabel('Photo file',{exact:true}).evaluate(e=>e.files[0].size),3600000)
  let attempts=[],lost=false,release;const hold=new Promise(resolve=>{release=resolve})
  await c.route(base,async route=>{if(route.request().method()==='POST'){attempts.push(route.request().headers()['x-evidence-id']);if(!lost){lost=true;await hold;const response=await route.fetch({timeout:90000});assert.equal(response.status(),200);return route.abort()}}return route.continue()})
  await p.getByRole('button',{name:'Upload photo',exact:true}).evaluate(b=>{b.click();b.click()});await expect(p.getByRole('button',{name:'Uploading…',exact:true})).toBeDisabled();await expect.poll(()=>attempts.length).toBe(1);release()
  await expect(p.getByRole('alert').filter({hasText:'Could not confirm the request'})).toBeVisible({timeout:90000});await expect(p.getByRole('status').filter({hasText:'Photo saved and retained.'})).toHaveCount(0);await expect(p.getByLabel('Photo caption',{exact:true})).toHaveValue(caption);await p.getByRole('button',{name:'Retry selected photo',exact:true}).click();await expect(p.getByRole('status').filter({hasText:'Photo saved and retained.'})).toBeVisible({timeout:90000});assert.equal(attempts.length,2);assert.equal(attempts[0],attempts[1]);await c.unroute(base)
  await p.reload({waitUntil:'networkidle'});await expect.poll(()=>p.getByRole('img',{name:caption,exact:true}).evaluate(e=>e.complete&&e.naturalWidth>0)).toBe(true);await expect(p.getByText(caption,{exact:true})).toBeVisible();const rows=await(await c.request.get(base)).json();assert.equal(rows.filter(r=>r.state==='ready').length,1);state.photoId=rows.find(r=>r.state==='ready').id;const photo=await c.request.get(base+'/'+state.photoId);assert.equal(photo.status(),200);const metadata=await sharp(await photo.body()).metadata();assert.equal(metadata.exif,undefined);state.photoHash=createHash('sha256').update(await photo.body()).digest('hex');state.photoInputBytes=fixture.length
  const [tab]=await Promise.all([p.waitForEvent('popup'),p.locator('.photo-preview').click()]);await tab.waitForLoadState();await expect.poll(()=>tab.locator('img').evaluate(e=>e.complete&&e.naturalWidth>0)).toBe(true);await tab.close();state.photoLayout=await p.evaluate(()=>({pageWidth:document.documentElement.scrollWidth,viewport:innerWidth,photoTop:document.querySelector('#photo-evidence').getBoundingClientRect().top+scrollY}));assert.ok(state.photoLayout.pageWidth<=state.photoLayout.viewport);await p.screenshot({path:output+'/photos.png',fullPage:true});pass('recognizable 3.43 MiB real upload, interruption retry, repeated taps and reload persistence')
 }
 if(!has('finalization, direct PDF action, retained download and PDF text')){
  await p.goto(report+'?step=4',{waitUntil:'networkidle'});if(await p.getByRole('button',{name:'Finalize report',exact:true}).count()){await expect(p.getByText('What happens when you finalize?',{exact:true})).toBeVisible();await p.getByRole('checkbox').check();await expect(p.getByRole('button',{name:'Finalize report',exact:true})).toBeEnabled();await p.screenshot({path:output+'/review.png',fullPage:true});await p.getByRole('button',{name:'Finalize report',exact:true}).evaluate(b=>{b.click();b.click()})}
  await expect(p.getByRole('button',{name:'Open PDF',exact:true})).toBeEnabled({timeout:90000});await expect(p.getByRole('button',{name:'Open PDF',exact:true})).toBeInViewport();state.pdfActionTop=await p.locator('#report-pdf').evaluate(e=>e.getBoundingClientRect().top+scrollY);await p.screenshot({path:output+'/finalized.png'})
  const popup=p.waitForEvent('popup');await p.getByRole('button',{name:'Open PDF',exact:true}).evaluate(b=>{b.click();b.click()});const viewer=await popup;await expect(p.getByRole('status').filter({hasText:'PDF sent to a new tab'})).toBeVisible({timeout:90000});await expect(p.getByRole('link',{name:'Open prepared PDF',exact:true})).toHaveAttribute('href',/^blob:/);await viewer.close()
  const downloading=p.waitForEvent('download');await p.getByRole('button',{name:'Download PDF',exact:true}).click();const download=await downloading;state.pdfPath=output+'/report.pdf';await download.saveAs(state.pdfPath)
  const job=await(await c.request.get(exports)).json();state.exportId=job.id;const bytes=await(await c.request.get(exports+'/'+job.id)).body();assert.deepEqual(readFileSync(state.pdfPath),bytes);state.pdfHash=createHash('sha256').update(bytes).digest('hex')
  const poppler=resolve('.staging/poppler-26.07.0-0/poppler-26.07.0/Library/bin/pdftotext.exe');assert.ok(existsSync(poppler),'Install approved Poppler to verify PDF text');const text=execFileSync(poppler,[state.pdfPath,'-'],{encoding:'utf8'});for(const expected of [address,note,'SYNTHETIC orange cone'])assert.ok(text.includes(expected),'PDF missing synthetic content');writeFileSync(output+'/report.txt',text);save();pass('finalization, direct PDF action, retained download and PDF text')
 }
 if(!has('separate amendment persistence, original immutable, retained hashes and access denial')){
  await p.goto(report,{waitUntil:'networkidle'});await p.getByRole('link',{name:'Make a correction',exact:true}).click();await expect(p.getByLabel('Reason for correction',{exact:true})).toBeInViewport()
  if(!state.amendmentId){await p.getByLabel('Reason for correction',{exact:true}).fill('SYNTHETIC journey correction '+label);await c.route(origin+'/api/workspace',async route=>{const data=route.request().postDataJSON();if(data.command==='amend'){state.amendmentId=data.payload.id;save()}return route.continue()});const response=p.waitForResponse(r=>r.url()===origin+'/api/workspace'&&r.request().postDataJSON()?.command==='amend');await p.getByRole('button',{name:'Create correction draft',exact:true}).evaluate(b=>{b.click();b.click()});assert.equal((await response).status(),200);await p.waitForURL(url=>url.pathname==='/report/'+state.amendmentId);await c.unroute(origin+'/api/workspace')}
  await p.goto(origin+'/report/'+state.amendmentId,{waitUntil:'networkidle'});await expect(p.getByLabel('Job address',{exact:true})).toHaveValue(address);await p.getByLabel('Client or job reference (optional)',{exact:true}).fill('SYNTHETIC amendment retained after reload');await saved();await p.reload({waitUntil:'networkidle'});await expect(p.getByLabel('Client or job reference (optional)',{exact:true})).toHaveValue('SYNTHETIC amendment retained after reload');await expect(p.getByRole('link',{name:'the original report',exact:true})).toHaveAttribute('href','/report/'+state.reportId);assert.deepEqual(await(await c.request.get(origin+'/api/reports/'+state.amendmentId+'/evidence')).json(),[])
  assert.equal(createHash('sha256').update(await(await c.request.get(exports+'/'+state.exportId)).body()).digest('hex'),state.pdfHash);assert.equal(createHash('sha256').update(await(await c.request.get(base+'/'+state.photoId)).body()).digest('hex'),state.photoHash)
  assert.equal((await ordinary.auth.signInWithPassword(secrets.owner)).error,null);const {data:original,error}=await ordinary.from('ts_reports').select('*').eq('id',state.reportId).single();assert.equal(error,null);const immutable=await c.request.post(origin+'/api/workspace',{headers:{origin},data:{command:'save_report',payload:{companyId,id:state.reportId,revision:original.revision,requestId:randomUUID(),document:original.document}}});assert.equal(immutable.status(),409);assert.equal((await immutable.json()).code,'immutable')
  const outsider=await browser.newContext(options);await login(outsider,{email:env.STAGING_OUTSIDER_EMAIL,password:env.STAGING_OUTSIDER_PASSWORD});for(const path of [base,base+'/'+state.photoId,exports+'/'+state.exportId])assert.equal((await outsider.request.get(path)).status(),404);await outsider.close();const anon=await browser.newContext(options);assert.equal((await anon.request.get(exports+'/'+state.exportId)).status(),401);await anon.close();pass('separate amendment persistence, original immutable, retained hashes and access denial')
 }
 state.status='PASS';delete state.failure
}catch(e){state.status='FAIL';state.failure={name:e.name,message:e.message.slice(0,1200),lines:[...(e.stack||'').matchAll(/report-journey\.mjs:(\d+)/g)].map(m=>Number(m[1]))};await p.screenshot({path:output+'/failure.png',fullPage:true}).catch(()=>{});process.exitCode=1}
finally{await browser.close();state.finishedAt=new Date().toISOString();save();console.log(JSON.stringify({status:state.status,checks:state.checks,failure:state.failure,reportId:state.reportId,sourceCommit:state.sourceCommit,sourceDirty:state.sourceDirty}))}
