// Immutable draft source-register version. New reviewed content requires a new version.
export const BRIEF_SOURCE_VERSION='on-construction-2026-09-21-draft-1'
export const BRIEF_SOURCE_RETRIEVED='2026-09-21'
export const BRIEF_SOURCES=[
 {id:'ohsa-duties',authority:'Ontario Legislature',source:'Occupational Health and Safety Act, R.S.O. 1990, c. O.1, ss. 25(2)(a),(h), 27(2)(a),(c), 28(1)(c),(d)',url:'https://www.ontario.ca/laws/statute/90o01',kind:'Legislation',jurisdiction:'Ontario; applicability and legal roles require confirmation',version:'Current consolidation/effective dates NOT verified: direct retrieval returned HTTP 403; official ministry indexed guidance corroborates duty references.',prompt:'What hazards need to be explained, who needs to hear about them, and what precautions will be checked?',review:'Pending qualified review; candidate reference, not a complete statement of duties'},
 {id:'construction-falls',authority:'Ontario Lieutenant Governor in Council',source:'O. Reg. 213/91, Construction Projects, s. 26 and ss. 26.1–26.9',url:'https://www.ontario.ca/laws/regulation/910213',kind:'Legislation',jurisdiction:'Ontario construction projects; task-specific applicability not determined by the app',version:'Current consolidation/effective dates NOT verified; direct retrieval HTTP 403. Indexed official text and ministry fall-prevention guidance inspected; stale indexed copies are not current-law confirmation.',prompt:'Could this task expose anyone to a fall? Record the planned protection, who will check it, and any unresolved concern.',review:'Pending qualified review; no heights, equipment specifications or standards reproduced'},
 {id:'ohsa-refusal',authority:'Ontario Legislature',source:'OHSA, s. 43; ministry Guide to the OHSA, Part V',url:'https://www.ontario.ca/document/guide-occupational-health-and-safety-act/part-v-right-refuse-or-stop-work-where-health-and-safety-danger',kind:'Legislation reference with ministry guidance',jurisdiction:'Ontario; statutory scope, exceptions and procedure require qualified review',version:'Guide indexed text retrieved; direct Ontario pages HTTP 403. Current legislative consolidation and guide revision date unverified.',prompt:'If work was paused, what was the concern and who was actually told? An app entry is not the statutory work-refusal process.',review:'Pending qualified review; no regulatory report or notification sent'},
 {id:'ministry-construction',authority:'Ontario Ministry of Labour, Immigration, Training and Skills Development',source:'Hazards in the construction sector; Construction hazards in active, existing workplaces',url:'https://www.ontario.ca/page/hazards-construction-sector',kind:'Official ministry guidance',jurisdiction:'Ontario construction, including interaction with occupied workplaces and other trades',version:'Indexed official guidance inspected on retrieval date; direct page HTTP 403; effective/revision date unverified.',prompt:'Consider nearby workers, occupants, moving equipment, energy, excavation, dust, weather and changes since the last visit. Add hazards specific to this task.',review:'Pending qualified review; examples are not a complete checklist'},
 {id:'ministry-roles',authority:'Ontario Ministry of Labour, Immigration, Training and Skills Development',source:'Supervisors under the OHSA; Constructor guideline; OHSA s. 1 definitions',url:'https://www.ontario.ca/page/supervisors-under-occupational-health-and-safety-act',kind:'Official ministry guidance',jurisdiction:'Ontario; actual workplace responsibilities determine legal roles',version:'Indexed official guidance inspected; direct page HTTP 403; current guide revision date unverified.',prompt:'Who is the site contact, and which workplace responsibilities have been confirmed outside the app? An app permission is not a legal-role designation.',review:'Pending qualified review'},
 {id:'ccohs-jsa',authority:'Canadian Centre for Occupational Health and Safety',source:'OSH Answers: Job Safety Analysis, steps, hazard identification, preventive measures and communication',url:'https://www.ccohs.ca/oshanswers/hsprograms/job-haz.html',kind:'Supporting guidance, not legislation',jurisdiction:'General Canadian guidance; site/jurisdiction applicability must be assessed',version:'Fact sheet last revised 2024-01-04; page metadata modified 2026-09-17; full page retrieved 2026-09-21.',prompt:'Break today’s task into steps. For each, describe what could cause harm and a specific control; consider eliminating the hazard before relying on procedures or PPE.',review:'Pending qualified review of proposed app prompt'},
 {id:'ihsa-talks',authority:'Infrastructure Health & Safety Association',source:'Safety Talks, introduction and record of date/topic/attendees',url:'https://www.ihsa.ca/resources/safetytalks.aspx',kind:'Supporting guidance, not legislation',jurisdiction:'Construction safety guidance; not a substitute for site-specific training',version:'Full public landing page retrieved 2026-09-21; no effective/revision date shown. Individual manuals/standards not reproduced.',prompt:'Discuss the actual task and changes with the crew. Record what was discussed and who was present; each signed-in participant acknowledges separately.',review:'Pending qualified review; attendance does not prove understanding'},
 {id:'recording-convention',authority:'TradeSafe staging product proposal',source:'Daily brief recording convention, draft version 1',url:'',kind:'Company-policy proposal / product convention, not legislation or adopted company policy',jurisdiction:'User-confirmed workplace; generic recording available outside Ontario construction',version:BRIEF_SOURCE_VERSION,prompt:'Reconfirm today’s context. Record proposed and reported-implemented controls separately; preserve prior briefings and request fresh acknowledgements after revision.',review:'Pending company adoption and qualified content/privacy review'},
] as const
