export const HANDOVER_ZONES=['America/Toronto','America/Winnipeg','UTC']
export function validHandoverDate(value){return typeof value==='string'&&/^20\d{2}-\d{2}-\d{2}$|^2100-\d{2}-\d{2}$/.test(value)&&Number.isFinite(Date.parse(value))&&new Date(value).toISOString().slice(0,10)===value}
export function todayInZone(zone='America/Toronto',now=new Date()){return new Intl.DateTimeFormat('en-CA',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit'}).format(now)}
export function handoverTime(value,zone){return new Intl.DateTimeFormat('en-CA',{timeZone:zone,dateStyle:'medium',timeStyle:'long'}).format(new Date(value))}
export const handoverState={open:'Open',in_progress:'In progress',awaiting_verification:'Awaiting verification',closed:'Closed — verified'}
export function originalLink(row){return row.concern_id?'/concerns/'+row.concern_id:row.brief_id?'/briefs/'+row.brief_id+'?version='+row.brief_version:'/report/'+row.report_id}
export function actionLink(row,site){return '/actions?'+new URLSearchParams({company:site.company_id,site:site.id,mine:'0',status:'all',focus:row.id})}
const e=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))
export function handoverExport(s,origin){
 const row=(label,value)=>`<p><strong>${e(label)}:</strong> ${e(value)}</p>`,link=(path,label)=>`<a href="${e(origin+path)}">${e(label)}</a>`,time=t=>handoverTime(t,s.timezone),section=(title,rows)=>`<section><h2>${e(title)}</h2>${rows||'<p>No permitted records in this section.</p>'}</section>`
 return `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Site handover — ${e(s.date)}</title><style>body{font:16px/1.5 system-ui;max-width:800px;margin:2rem auto;padding:0 1rem;color:#111}article{border-top:1px solid #aaa;padding:1rem 0;break-inside:avoid}p{white-space:pre-wrap;overflow-wrap:anywhere}a{overflow-wrap:anywhere}</style><body><h1>Site handover</h1>${row('Site',s.site.document.name)}${row('Location',s.site.document.address)}${row('Site ID / current detail revision',s.site.id+' / '+s.site.revision)}${row('Company',s.company)}${row('Selected day',s.date)}${row('Timezone',s.timezone)}${row('Day boundaries (inclusive start, exclusive end)',s.start+' to '+s.end)}${row('Generated at',s.generatedAt)}<p>Permission-scoped snapshot. Selected-day activity uses server recording/submission/verification timestamps. Outstanding work is current as of generation, including earlier days; it does not reconstruct historical status. Planning due dates use America/Toronto and are human-entered, not safety ratings or legal deadlines. Names are current member labels unless captured in a briefing. Links require authentication and current access. No photo bytes are included.</p>
 ${section('Outstanding now ('+s.outstanding.length+')',s.outstanding.map(a=>`<article>${link(actionLink(a,s.site),a.observation)}${row('Current status',handoverState[a.state])}${row('Responsible',a.responsible+(a.needs_reassignment?' — needs assignment/reassignment':''))}${row('Due date (planning, America/Toronto)',a.target_date||'Unscheduled')}${row('Operational priority',a.priority||'Not recorded')}${row('Progress',a.resolution||'None recorded')}${link(originalLink(a),'Original record')}</article>`).join(''))}
 ${section('Briefing versions recorded on selected day ('+s.briefs.length+')',s.briefs.map(b=>`<article>${link('/briefs/'+b.id+'?version='+b.version,'Brief '+b.id+' — version '+b.version)}${row('Task / entered work date',b.task+' / '+b.workDate)}${row('Recorded',b.recordedBy+' at '+time(b.recordedAt))}${row('Acknowledgements of this exact version, as of generation',b.acknowledgements.length+' / '+b.participants.length)}${row('Included participants',(b.participants||[]).map(id=>b.people?.find(p=>p.id===id)?.name||id).join(', '))}${row('Attendance entered by recorder',(b.attendance||[]).map(id=>b.people?.find(p=>p.id===id)?.name||id).join(', ')||'None recorded')}${b.acknowledgements.map(a=>row('Authenticated acknowledgement',a.name+' at '+time(a.at))).join('')}</article>`).join(''))}
 ${section('Concerns submitted on selected day ('+s.concerns.length+')',s.concerns.map(c=>`<article>${link('/concerns/'+c.id,c.document.observation)}${row('Location',c.document.location)}${row('Submitted',c.reporter+' at '+time(c.submitted_at))}${row('User-entered observation time',c.document.observedAt||'Not entered')}${c.followUp?link(actionLink(c.followUp,s.site),'Follow-up action')+row('Follow-up now',handoverState[c.followUp.state]+' / '+c.followUp.responsible)+row('Progress',c.followUp.resolution||'None recorded')+(c.followUp.verified_at?row('Current closure verification',c.followUp.verifiedBy+' at '+time(c.followUp.verified_at)):''):'<p>No follow-up record available.</p>'}</article>`).join(''))}
 ${section('Verification events on selected day ('+s.closures.length+')',s.closures.map(a=>`<article>${link(actionLink(a,s.site),a.observation)}${row('Verified closed',a.verifiedBy+' at '+time(a.at))}${row('Responsible at verification',a.responsible)}${row('Resolution at verification',a.resolution)}${row('Current status at generation',handoverState[a.currentState])}${link(originalLink(a),'Original record')}</article>`).join(''))}
 <p>A missing acknowledgement does not establish absence. Attendance and authenticated acknowledgement are different; neither proves understanding or qualification. A closed action does not certify the site safe. Safety content remains draft pending qualified review. This handover sends no notifications and is not work authorization.</p></body></html>`
}
