'use client'
import { useState } from 'react'
import { command } from '@/lib/client/commands'
const fields={contact_email:'Contact email',contact_phone:'Contact phone',address:'Business address',license_number:'Trade licence / registration reference',ecra_number:'ECRA / ESA reference',coq_number:'Certificate of qualification reference',cot_cert_number:'Other recorded trade certificate reference',wah_cert_number:'Working at heights training reference',wsib_number:'WSIB reference',liability_policy_number:'Liability policy reference'}
export default function CompanySettings({company,members,invitations,role,actor}) {
 const [name,setName]=useState(company.name),[business,setBusiness]=useState(company.business),[revision,setRevision]=useState(company.revision),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[email,setEmail]=useState(''),[inviteRole,setInviteRole]=useState('worker'),[link,setLink]=useState('')
 async function run(task){setBusy(true);setMessage('');try{await task()}catch(e){setMessage(e.message)}finally{setBusy(false)}}
 async function save(e){e.preventDefault();await run(async()=>{const c=await command('save_company',{companyId:company.id,name,business,revision});setRevision(c.revision);setMessage('Company details saved. New drafts will use these details.')})}
 async function invite(e){e.preventDefault();await run(async()=>{const r=await command('invite',{companyId:company.id,email,role:inviteRole});setLink(r.link);setMessage('Invitation created. Share the link privately with the intended person. It expires in seven days. No email has been sent.')})}
 async function changeMember(userId,newRole){if(!confirm(newRole==='remove'?'Remove this member’s company access? Existing records and actions will remain.':'Change this member’s access role?'))return;await run(async()=>{await command('member',{companyId:company.id,userId,role:newRole});window.location.reload()})}
 return <><h1>Company & people</h1><p>Your access: <strong>{role}</strong>. Roles control this application; they do not establish trade qualifications or legal authority.</p>
 <section className="work-panel"><h2>Business details</h2><form onSubmit={save}><fieldset className="work-fieldset" disabled={role!=='owner'||busy}><label htmlFor="business-name">Business name</label><input id="business-name" value={name} required maxLength={200} onChange={e=>setName(e.target.value)}/>{Object.entries(fields).map(([key,label])=><div key={key}><label htmlFor={'business-'+key}>{label} (optional)</label><input id={'business-'+key} maxLength={1000} value={business[key]||''} onChange={e=>setBusiness({...business,[key]:e.target.value})}/></div>)}<button className="primary">Save business details</button></fieldset></form></section>
 {!!Object.keys(company.legacy_profiles).length&&<details className="work-panel"><summary>Previous business details retained for review</summary><p>Both historical profiles are preserved. Saved business settings take precedence for new drafts. Review differences before relying on prefilled details.</p>{Object.entries(company.legacy_profiles).filter(([,value])=>value).map(([source,value])=><section key={source}><h3>{source==='profile'?'Original report profile':'Original business settings'}</h3><dl>{Object.entries(value).filter(([k])=>!['id','user_id','created_at','updated_at'].includes(k)).map(([k,v])=><div key={k}><dt>{fields[k]||k.replaceAll('_',' ')}</dt><dd>{String(v??'Not recorded')}</dd></div>)}</dl></section>)}</details>}
 <section className="work-panel"><h2>Company members</h2><ul className="work-list">{members.map(m=><li key={m.user_id}><strong>{m.display_name}{m.user_id===actor?' (you)':''}</strong><p>{m.active?m.role:'Access removed'}</p>{role==='owner'&&m.active&&<div className="work-buttons"><label htmlFor={'role-'+m.user_id}>Access role</label><select id={'role-'+m.user_id} value={m.role} disabled={busy} onChange={e=>changeMember(m.user_id,e.target.value)}>{['worker','supervisor','owner'].map(r=><option key={r}>{r}</option>)}</select><button disabled={busy} onClick={()=>changeMember(m.user_id,'remove')}>Remove access</button></div>}</li>)}</ul><p>Reassign open actions belonging to removed members from the Actions page.</p></section>
 {role==='owner'&&<section className="work-panel"><h2>Invite a person</h2><form onSubmit={invite}><label htmlFor="invite-email">Their sign-in email</label><input id="invite-email" type="email" required maxLength={254} value={email} onChange={e=>setEmail(e.target.value)}/><label htmlFor="invite-role">Access role</label><select id="invite-role" value={inviteRole} onChange={e=>setInviteRole(e.target.value)}>{['worker','supervisor','owner'].map(r=><option key={r}>{r}</option>)}</select><button disabled={busy}>Create invitation link</button></form>{link&&<><label htmlFor="invite-link">Private invitation link</label><input id="invite-link" readOnly value={link} onFocus={e=>e.target.select()}/><p>Copy this link and share it with the intended person. The link is shown only here; create a new invitation if it is lost.</p></>}
 <h3>Recent invitations</h3><ul>{invitations.map(i=><li key={i.id}>{i.email} · {i.role} · {i.revoked?'Revoked':i.accepted_by?'Accepted':new Date(i.expires_at)<new Date()?'Expired':'Pending'}{!i.revoked&&!i.accepted_by&&<button disabled={busy} onClick={()=>run(async()=>{await command('revoke_invitation',{companyId:company.id,id:i.id});window.location.reload()})}>Revoke invitation</button>}</li>)}</ul></section>}
 {message&&<p className="work-alert" role="status">{message}</p>}<p>Payments are currently unavailable. Existing payment history is preserved; it does not grant safety status.</p></>
}
