'use client'
import { useRef,useState } from 'react'
import { command } from '@/lib/client/commands'
const fields={contact_email:'Contact email',contact_phone:'Contact phone',address:'Business address',license_number:'Trade licence / registration reference',ecra_number:'ECRA / ESA reference',coq_number:'Certificate of qualification reference',cot_cert_number:'Other recorded trade certificate reference',wah_cert_number:'Working at heights training reference',wsib_number:'WSIB reference',liability_policy_number:'Liability policy reference'}
export default function CompanySettings({company,members,invitations,role,actor,accountEmail}) {
 const [name,setName]=useState(company.name),[business,setBusiness]=useState(company.business),[revision,setRevision]=useState(company.revision),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[email,setEmail]=useState(''),[inviteRole,setInviteRole]=useState('worker'),[link,setLink]=useState('')
 const lock=useRef(false)
 const [invitationRows,setInvitationRows]=useState(invitations),[memberRows,setMemberRows]=useState(members),[copied,setCopied]=useState('')
 const onlyOwner=memberRows.filter(m=>m.active&&m.role==='owner').length===1
 async function copyLink(){try{await navigator.clipboard.writeText(link);setCopied('Invitation link copied. Share it privately.')}catch{setCopied('Copy was unavailable. Select the private link and copy it manually.')}}
 const [area,setArea]=useState(''),[error,setError]=useState('')
 const feedback=where=>area===where&&<div aria-busy={busy}>{message&&<p role="status">{message}</p>}{error&&<div role="alert"><p>{error}</p><a href="/auth/login" target="_blank" rel="noopener noreferrer">Sign in in another tab, then return here</a>{where==='invite'&&<p>If no link was confirmed, review recent invitations before creating another. An interrupted request may already have created one.</p>}</div>}</div>
 async function run(task,where='members'){if(lock.current)return;lock.current=true;setArea(where);setBusy(true);setError('');setMessage('Working. Keep this page open.');try{await task()}catch(e){setMessage('');setError(e.message)}finally{lock.current=false;setBusy(false)}}
 async function save(e){e.preventDefault();await run(async()=>{const c=await command('save_company',{companyId:company.id,name,business,revision});setRevision(c.revision);setMessage('Company details saved. New drafts will use these details.')},'business')}
 async function invite(e){e.preventDefault();await run(async()=>{const r=await command('invite',{companyId:company.id,email,role:inviteRole});setLink(r.link);setCopied('');setInvitationRows(rows=>[{id:r.id,email,role:inviteRole,expires_at:r.expires_at},...rows]);setMessage('Invitation created. Share the link privately with the intended person. It expires in seven days. No email has been sent.')},'invite')}
 async function changeMember(userId,newRole){if(!confirm(newRole==='remove'?'Remove this member’s company access? Existing records and actions will remain.':'Change this member’s access role?'))return;await run(async()=>{await command('member',{companyId:company.id,userId,role:newRole});setMemberRows(rows=>rows.map(m=>m.user_id===userId?{...m,active:newRole!=='remove',role:newRole==='remove'?m.role:newRole}:m));setMessage('Company access updated. Existing records remain unchanged.');if(userId===actor)window.location.reload()})}
 return <><h1>Settings</h1><nav className="settings-nav" aria-label="Settings sections"><a href="#account-settings">Your account</a><a href="#company-settings">Company profile</a><a href="#crew-settings">Crew</a>{role==='owner'&&<a href="#invitation-settings">Invitations</a>}</nav><section id="account-settings" className="daily-section"><h2>Your account</h2><dl><dt>Name</dt><dd>{members.find(m=>m.user_id===actor)?.display_name||'Not recorded'}</dd><dt>Sign-in email</dt><dd>{accountEmail}</dd></dl><p>Your account profile is shown as recorded. Profile editing is not currently available.</p><div className="work-buttons"><a href="/auth/forgot-password">Password recovery</a><a href="/join">Join another crew</a></div></section><p>Your access: <strong>{role}</strong>. Roles control this application; they do not establish trade qualifications or legal authority.</p>
 {role==='owner'&&<section id="invitation-settings" className="daily-section"><h2>Invite a person</h2><p>Workers can record reports and update their assigned actions. Supervisors can also edit crew reports and verify actions. Owners additionally manage the company and crew.</p><form onSubmit={invite}><label htmlFor="invite-email">Their sign-in email</label><input id="invite-email" disabled={busy} type="email" required maxLength={254} value={email} onChange={e=>setEmail(e.target.value)}/><label htmlFor="invite-role">Access role</label><select id="invite-role" disabled={busy} value={inviteRole} onChange={e=>setInviteRole(e.target.value)}>{['worker','supervisor','owner'].map(r=><option key={r}>{r}</option>)}</select><button disabled={busy}>{busy&&area==='invite'?'Creating invitation...':'Create invitation link'}</button>{feedback('invite')}</form>{link&&<><label htmlFor="invite-link">Private invitation link</label><input id="invite-link" readOnly value={link} onFocus={e=>e.target.select()}/><button type="button" onClick={copyLink}>Copy invitation link</button>{copied&&<p role="status">{copied}</p>}<p>Copy this link and share it with the intended person. The link is shown only here; create a new invitation if it is lost.</p></>}
 <h3>Recent invitations</h3>{!invitationRows.length&&<p>No invitations yet. Create a private link above; no email is sent.</p>}<ul>{invitationRows.map(i=><li key={i.id}>{i.email} · {i.role} · {i.revoked?'Revoked':i.accepted_by?'Accepted':new Date(i.expires_at)<new Date()?'Expired':'Pending'}{!i.revoked&&!i.accepted_by&&<button disabled={busy} onClick={()=>run(async()=>{await command('revoke_invitation',{companyId:company.id,id:i.id});setInvitationRows(rows=>rows.map(row=>row.id===i.id?{...row,revoked:true}:row));setMessage('Invitation revoked. The link can no longer grant access.')},'invite')}>Revoke invitation</button>}</li>)}</ul></section>}
 <section id="company-settings" className="daily-section"><h2>Business details</h2><p>Only the business name is required. Optional details can be completed later. Changes apply to new drafts; historical report snapshots remain unchanged.</p>{role!=='owner'&&<p>Only company owners can change these details or manage invitations and roles.</p>}<form onSubmit={save}><fieldset className="work-fieldset" disabled={role!=='owner'||busy}><label htmlFor="business-name">Business name</label><input id="business-name" value={name} required maxLength={200} onChange={e=>setName(e.target.value)}/><details><summary>Optional contact and trade details</summary>{Object.entries(fields).map(([key,label])=><div key={key}><label htmlFor={'business-'+key}>{label} (optional)</label><input id={'business-'+key} maxLength={1000} value={business[key]||''} onChange={e=>setBusiness({...business,[key]:e.target.value})}/></div>)}</details>{role==='owner'&&<button className="primary">{busy&&area==='business'?'Saving...':'Save business details'}</button>}</fieldset>{feedback('business')}</form></section>
 {!!Object.keys(company.legacy_profiles).length&&<details className="work-panel"><summary>Previous business details retained for review</summary><p>Both historical profiles are preserved. Saved business settings take precedence for new drafts. Review differences before relying on prefilled details.</p>{Object.entries(company.legacy_profiles).filter(([,value])=>value).map(([source,value])=><section key={source}><h3>{source==='profile'?'Original report profile':'Original business settings'}</h3><dl>{Object.entries(value).filter(([k])=>!['id','user_id','created_at','updated_at'].includes(k)).map(([k,v])=><div key={k}><dt>{fields[k]||k.replaceAll('_',' ')}</dt><dd>{String(v??'Not recorded')}</dd></div>)}</dl></section>)}</details>}
 <section id="crew-settings" className="daily-section"><h2>Company members</h2><ul className="work-list">{memberRows.map(m=><li key={m.user_id}><strong>{m.display_name}{m.user_id===actor?' (you)':''}</strong><p>{m.active?m.role:'Access removed'}</p>{role==='owner'&&m.active&&<div className="work-buttons"><label htmlFor={'role-'+m.user_id}>Access role</label><select id={'role-'+m.user_id} value={m.role} disabled={busy||(onlyOwner&&m.role==='owner')} onChange={e=>changeMember(m.user_id,e.target.value)}>{['worker','supervisor','owner'].map(r=><option key={r}>{r}</option>)}</select><button disabled={busy||(onlyOwner&&m.role==='owner')} onClick={()=>changeMember(m.user_id,'remove')}>Remove access</button></div>}</li>)}</ul>{onlyOwner&&role==='owner'&&<p>Add another owner before changing or removing the last owner.</p>}<p>Reassign open actions belonging to removed members from the Actions page.</p>{feedback('members')}</section>

 <p>Payments are currently unavailable. Existing payment history is preserved; it does not grant safety status.</p></>
}
