'use client'
import {useRef,useState} from 'react'
import {useClientReady} from '@/lib/client/useClientReady'
import {useDraft} from '@/lib/client/useDraft'
import {briefCommand,saveBrief} from '@/lib/client/brief-command'
import PromptPanel from '../PromptPanel'
const stages=['Site','Today’s work','Hazards and controls','Crew briefing']
export default function BriefEditor({initial,actor,members,editable,initialStep,previousVersion,contentCatalog}){
 const ready=useClientReady(),draft=useDraft(initial,actor,saveBrief),d=draft.document
 const [step,setStep]=useState(Math.max(1,Math.min(4,initialStep))),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const request=useRef(null),lock=useRef(false)
 const change=(key,value)=>draft.change(current=>({...current,[key]:typeof value==='function'?value(current[key]):value,...(['jurisdiction','workplace'].includes(key)&&current.promptTask?{promptTask:''}:{})}))
 const people=members.filter(m=>m.active||d.crew.includes(m.user_id)),name=id=>members.find(m=>m.user_id===id)?.display_name||'Former member'
 function go(n){setStep(n);window.history.replaceState(null,'','?step='+n);requestAnimationFrame(()=>document.getElementById('brief-step')?.focus())}
 function setHazard(id,key,value){change('steps',steps=>steps.map(s=>s.id===id?{...s,[key]:value}:s))}
 const field=(key,label,type='text')=><div><label htmlFor={'brief-'+key}>{label}</label><input id={'brief-'+key} type={type} maxLength={2000} value={d[key]} onChange={e=>change(key,e.target.value)}/></div>
 async function record(){if(lock.current||!ready)return;lock.current=true;setBusy(true);setError('');try{
  if(!await draft.flush()){setError('Save the draft before recording the briefing. Your entries remain here.');return}
  request.current||={id:initial.id,companyId:initial.company_id,revision:draft.revision.current,requestId:crypto.randomUUID()}
  await briefCommand('record',request.current,actor)
  // Load the authoritative recorded version after a confirmed or idempotently recovered result.
  // Full navigation discards the confirmed draft buffer and loads the recorded version.
  // eslint-disable-next-line @next/next/no-location-assign-relative-destination
  window.location.assign('/briefs/'+initial.id)
 }catch(e){setError(e.code==='incomplete'?'Complete site, date, context confirmation, work, contact, crew, each hazard/control/responsible person and briefing notes. Attendance is recorded separately from acknowledgement.':e.message);if(['incomplete','invalid_request'].includes(e.code))request.current=null}finally{lock.current=false;setBusy(false)}}
 return <div className="brief-journey"><p className="eyebrow">Daily brief draft · revision {draft.revision.current}</p><h1>{d.site||'Today’s site brief'}</h1>{previousVersion&&<p>Saved draft. Any earlier briefing and acknowledgements remain in version history; they do not acknowledge this revision. <a href={'/briefs/'+initial.id+'?version='+previousVersion}>Previous recorded version</a></p>}{!editable&&<p role="alert">Read only. The author, an app supervisor or owner can edit this draft.</p>}<nav className="work-steps" aria-label="Daily brief steps">{stages.map((label,i)=><button key={label} type="button" disabled={!ready||busy} aria-current={step===i+1?'step':undefined} onClick={()=>go(i+1)}>{i+1}. {label}</button>)}</nav><h2 id="brief-step" tabIndex={-1}>{stages[step-1]}</h2>
 <fieldset className="work-fieldset" disabled={!ready||!editable||busy||Boolean(request.current)||draft.blocked.current}>
 {step===1&&<section>{field('site','Site name or address')}{field('date','Work date','date')}<label htmlFor="brief-jurisdiction">Jurisdiction</label><select id="brief-jurisdiction" value={d.jurisdiction} onChange={e=>change('jurisdiction',e.target.value)}><option value="">Choose jurisdiction</option><option value="CA-ON">Ontario, Canada</option><option value="other">Other / needs clarification</option></select><label htmlFor="brief-workplace">Workplace context</label><select id="brief-workplace" value={d.workplace} onChange={e=>change('workplace',e.target.value)}><option value="">Choose workplace context</option><option value="construction">Construction project</option><option value="other">Other / needs clarification</option></select><label className="work-check"><input type="checkbox" checked={d.confirmed} onChange={e=>change('confirmed',e.target.checked)}/>I have checked the jurisdiction and workplace context for this record.</label><p>This is your recorded context, not an app determination of which law applies. Other contexts use generic recording only.</p></section>}
 {step===2&&<section>{field('task','Today’s work')}{field('contact','Responsible site contact')}<p>Record a name and a way to reach them. This does not appoint a legal constructor or competent person.</p><h3>Participating crew</h3>{people.map(m=><label className="work-check" key={m.user_id}><input type="checkbox" disabled={!m.active} checked={d.crew.includes(m.user_id)} onChange={e=>{const checked=e.target.checked;draft.change(current=>{const crew=checked?[...current.crew,m.user_id]:current.crew.filter(id=>id!==m.user_id);return {...current,crew,attendance:current.attendance.filter(id=>crew.includes(id))}})}}/>{m.display_name}{!m.active?' (access removed)':''}</label>)}</section>}
 {step===3&&<section><PromptPanel document={d} catalog={contentCatalog} change={draft.change} companyId={initial.company_id}/><p>Your task, hazard and control entries below are user-entered records, not source text or approval.</p>
 {d.steps.map((s,i)=><fieldset className="work-panel" key={s.id}><legend>Task step {i+1}</legend>{[['task','Task step'],['hazard','Hazard or concern'],['control','Control or precaution']].map(([key,label])=><div key={key}><label htmlFor={key+'-'+s.id}>{label}</label><textarea id={key+'-'+s.id} maxLength={2000} value={s[key]} onChange={e=>setHazard(s.id,key,e.target.value)}/></div>)}<label htmlFor={'control-state-'+s.id}>Control status</label><select id={'control-state-'+s.id} value={s.controlState} onChange={e=>setHazard(s.id,'controlState',e.target.value)}><option value="proposed">Proposed — not confirmed implemented</option><option value="reported_implemented">Reported implemented</option></select><p>Only an app supervisor or owner can separately record a review of a recorded version. Review is not work authorization.</p><label htmlFor={'responsible-'+s.id}>Responsible for this control</label><select id={'responsible-'+s.id} value={s.responsible} onChange={e=>setHazard(s.id,'responsible',e.target.value)}><option value="">Choose a company member</option>{members.filter(m=>m.active||m.user_id===s.responsible).map(m=><option key={m.user_id} value={m.user_id} disabled={!m.active}>{m.display_name}</option>)}</select><p>Control responsibility is part of this assessment. Worker-created follow-ups start assigned to the recorder; a supervisor or owner can reassign them in Actions.</p><label className="work-check"><input type="checkbox" checked={s.unresolved} onChange={e=>setHazard(s.id,'unresolved',e.target.checked)}/>Unresolved concern — keep in Actions</label><button type="button" onClick={()=>change('steps',steps=>steps.filter(x=>x.id!==s.id))}>Remove task step {i+1} from this draft</button></fieldset>)}<button type="button" disabled={d.steps.length>=20} onClick={()=>change('steps',steps=>[...steps,{id:crypto.randomUUID(),task:'',hazard:'',control:'',controlState:'proposed',responsible:'',unresolved:true}])}>Add task step and hazard</button><p>Up to 20 entries. Use separate entries for additional hazards in a task step.</p><label className="work-check"><input type="checkbox" checked={d.paused} onChange={e=>change('paused',e.target.checked)}/>Work was paused</label>{d.paused&&field('pauseReason','Why work was paused')}{field('communication','Concern communication (who, how and when)')}<p>Leave blank if not communicated. Saving does not send a notification. A pause entry is not the statutory work-refusal process; use the applicable workplace procedure.</p></section>}
 {step===4&&<section><p>{d.site||'Site missing'} · {d.date||'Work date missing'} · {d.steps.length} task/hazard entries</p><p>Recording preserves this assessment as an immutable version. Changes require a new revision and fresh acknowledgement. Unresolved concerns create or retain linked Actions; recording does not resolve them or notify anyone.</p><label htmlFor="briefing-note">What was discussed in the briefing?</label><textarea id="briefing-note" maxLength={2000} value={d.briefingNote} onChange={e=>change('briefingNote',e.target.value)}/><h3>Attendance entered by you</h3>{d.crew.map(id=><label className="work-check" key={id}><input type="checkbox" checked={d.attendance.includes(id)} onChange={e=>change('attendance',attendance=>e.target.checked?[...attendance,id]:attendance.filter(x=>x!==id))}/>{name(id)}</label>)}<p>Attendance you enter is not the worker’s authenticated acknowledgement. Neither proves understanding, qualification or a digital signature.</p></section>}
 </fieldset>
 {(draft.error||error)&&<div role="alert"><p>{draft.error||error}</p><p>Your entries stay on this open page. For a stale revision, compare the latest record in another tab; no automatic merge is performed.</p><a target="_blank" rel="noopener noreferrer" href={'/briefs/'+initial.id}>Open latest brief</a><p><a target="_blank" rel="noopener noreferrer" href={'/auth/login?'+new URLSearchParams({redirect:'/briefs/'+initial.id})}>Sign in in another tab</a></p></div>}
 <div className="report-action-bar"><div><span className="save-state" role="status">{draft.status}</span>{draft.error&&<button disabled={!ready||draft.blocked.current||busy} onClick={draft.save}>Retry saving</button>}<p className="work-footnote">Wait for Saved before leaving. No offline or closed-browser recovery is promised.</p></div><div className="journey-actions">{step>1&&<button disabled={!ready||busy} onClick={()=>go(step-1)}>Back</button>}{step<4?<button className="primary" disabled={!ready||busy} onClick={()=>go(step+1)}>Continue</button>:<button className="primary" disabled={!ready||!editable||busy||draft.blocked.current} onClick={record}>{busy?'Recording briefing…':request.current?'Retry recording briefing':'Record briefing version'}</button>}</div></div></div>
}
